import 'ai_content.dart';

/// Defines the role of the message sender.
enum AiMessageRole {
  /// High-level instructions that steer the model's behaviour.
  ///
  /// Gemini and Anthropic receive these as their dedicated system prompt.
  system,

  /// Developer instructions (OpenAI's successor to `system`).
  ///
  /// Sent as `system` to providers that have no separate developer role.
  developer,

  /// Input from the end user.
  user,

  /// Output generated by the model, including tool calls.
  assistant,

  /// Results of tool executions ([AiToolResultContent]).
  tool,
}

/// Represents a single message in a conversation.
class AiMessage {
  /// The role of the message sender.
  final AiMessageRole role;

  /// The content of the message.
  final List<AiContent> content;

  /// Creates a message from a list of [content] parts.
  const AiMessage({
    required this.role,
    required this.content,
  });

  /// Convenience constructor for a message containing only text.
  factory AiMessage.text({
    required AiMessageRole role,
    required String text,
  }) {
    return AiMessage(
      role: role,
      content: [AiTextContent(text)],
    );
  }

  /// Convenience constructor for a system message.
  factory AiMessage.system(String text) {
    return AiMessage.text(
      role: AiMessageRole.system,
      text: text,
    );
  }

  /// Convenience constructor for a developer message.
  factory AiMessage.developer(String text) {
    return AiMessage.text(
      role: AiMessageRole.developer,
      text: text,
    );
  }

  /// Convenience constructor for a user message.
  factory AiMessage.user(String text) {
    return AiMessage.text(
      role: AiMessageRole.user,
      text: text,
    );
  }

  /// Convenience constructor for an assistant message.
  factory AiMessage.assistant(String text) {
    return AiMessage.text(
      role: AiMessageRole.assistant,
      text: text,
    );
  }

  /// Convenience constructor for a tool response message.
  factory AiMessage.tool(String text) {
    return AiMessage.text(
      role: AiMessageRole.tool,
      text: text,
    );
  }

  /// All [AiTextContent] parts of this message joined with newlines.
  ///
  /// Returns an empty string when the message has no text parts.
  String get text {
    return content.whereType<AiTextContent>().map((e) => e.text).join('\n');
  }
}
