import '../models/ai_finish_reason.dart';
import '../models/ai_message.dart';
import '../models/ai_usage.dart';

/// Represents a response from an AI provider.
class AiResponse {
  /// The message generated by the AI model.
  final AiMessage message;

  /// The reason why the generation stopped.
  final AiFinishReason finishReason;

  /// Information about the token usage for this request.
  final AiUsage usage;

  /// The raw JSON response from the provider (optional, for advanced use cases).
  final Map<String, dynamic>? raw;

  /// Creates a response.
  const AiResponse({
    required this.message,
    this.finishReason = AiFinishReason.unknown,
    this.usage = AiUsage.empty,
    this.raw,
  });

  /// Convenience getter for the generated text ([AiMessage.text]).
  String get text => message.text;
}
